// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// chk_omp
bool chk_omp();
RcppExport SEXP _BayesDecon_chk_omp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(chk_omp());
    return rcpp_result_gen;
END_RCPP
}
// formcorr
arma::mat formcorr(arma::vec b, arma::vec theta);
RcppExport SEXP _BayesDecon_formcorr(SEXP bSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(formcorr(b, theta));
    return rcpp_result_gen;
END_RCPP
}
// mcmcmvt_cpp
Rcpp::List mcmcmvt_cpp(arma::uword nsamp, arma::uword nburn, arma::uword nthin, arma::uword niter_u, arma::mat ws, arma::mat xs, arma::mat us, arma::uvec mis, arma::uword p, arma::uword q, arma::mat knots_t, arma::vec delta_t, arma::mat thetas, arma::mat theta_x, arma::umat z_u, arma::mat pi_u, arma::umat ic, arma::umat inc, arma::mat x_e, arma::mat x_nz, arma::mat theta_e, arma::umat z_x, arma::mat pi_x, arma::cube params_x, arma::mat P_t, arma::cube prop_sig_thetas, arma::cube prop_sig_thetas_x_density, arma::vec xs_lwr, arma::vec xs_upr, arma::uword x_grd_res, arma::uword var_grd_res, arma::uword e_grd_res, double alpha_x, double a_sigmasq_x, double b_sigmasq_x, arma::uword K_x, double a_vartheta, double b_vartheta, bool type_v, arma::uword K_t, arma::uword type_u, arma::uword K_epsilon, double alpha_epsilon, double a_epsilon, double b_epsilon, double sigmasq_epsilon, arma::vec a_xi, arma::vec b_xi, arma::vec sigmasq_xi, arma::vec a_beta, arma::vec b_beta, arma::vec sigmasq_beta, arma::mat mu0_thetas_eps, double sigma00_thetas_eps, double sig_tune_theta_1, double sig_tune_theta_2, bool show_progress);
RcppExport SEXP _BayesDecon_mcmcmvt_cpp(SEXP nsampSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP niter_uSEXP, SEXP wsSEXP, SEXP xsSEXP, SEXP usSEXP, SEXP misSEXP, SEXP pSEXP, SEXP qSEXP, SEXP knots_tSEXP, SEXP delta_tSEXP, SEXP thetasSEXP, SEXP theta_xSEXP, SEXP z_uSEXP, SEXP pi_uSEXP, SEXP icSEXP, SEXP incSEXP, SEXP x_eSEXP, SEXP x_nzSEXP, SEXP theta_eSEXP, SEXP z_xSEXP, SEXP pi_xSEXP, SEXP params_xSEXP, SEXP P_tSEXP, SEXP prop_sig_thetasSEXP, SEXP prop_sig_thetas_x_densitySEXP, SEXP xs_lwrSEXP, SEXP xs_uprSEXP, SEXP x_grd_resSEXP, SEXP var_grd_resSEXP, SEXP e_grd_resSEXP, SEXP alpha_xSEXP, SEXP a_sigmasq_xSEXP, SEXP b_sigmasq_xSEXP, SEXP K_xSEXP, SEXP a_varthetaSEXP, SEXP b_varthetaSEXP, SEXP type_vSEXP, SEXP K_tSEXP, SEXP type_uSEXP, SEXP K_epsilonSEXP, SEXP alpha_epsilonSEXP, SEXP a_epsilonSEXP, SEXP b_epsilonSEXP, SEXP sigmasq_epsilonSEXP, SEXP a_xiSEXP, SEXP b_xiSEXP, SEXP sigmasq_xiSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP sigmasq_betaSEXP, SEXP mu0_thetas_epsSEXP, SEXP sigma00_thetas_epsSEXP, SEXP sig_tune_theta_1SEXP, SEXP sig_tune_theta_2SEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type niter_u(niter_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type us(usSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mis(misSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type knots_t(knots_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_t(delta_tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta_x(theta_xSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type z_u(z_uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pi_u(pi_uSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type ic(icSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type inc(incSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_e(x_eSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_nz(x_nzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta_e(theta_eSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type z_x(z_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pi_x(pi_xSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type params_x(params_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_t(P_tSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type prop_sig_thetas(prop_sig_thetasSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type prop_sig_thetas_x_density(prop_sig_thetas_x_densitySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xs_lwr(xs_lwrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xs_upr(xs_uprSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type x_grd_res(x_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type var_grd_res(var_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type e_grd_res(e_grd_resSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_x(alpha_xSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigmasq_x(a_sigmasq_xSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigmasq_x(b_sigmasq_xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_x(K_xSEXP);
    Rcpp::traits::input_parameter< double >::type a_vartheta(a_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type b_vartheta(b_varthetaSEXP);
    Rcpp::traits::input_parameter< bool >::type type_v(type_vSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_t(K_tSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type type_u(type_uSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_epsilon(K_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_epsilon(alpha_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type a_epsilon(a_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type b_epsilon(b_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_epsilon(sigmasq_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_xi(a_xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_xi(b_xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigmasq_xi(sigmasq_xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigmasq_beta(sigmasq_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu0_thetas_eps(mu0_thetas_epsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma00_thetas_eps(sigma00_thetas_epsSEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_theta_1(sig_tune_theta_1SEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_theta_2(sig_tune_theta_2SEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcmvt_cpp(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, p, q, knots_t, delta_t, thetas, theta_x, z_u, pi_u, ic, inc, x_e, x_nz, theta_e, z_x, pi_x, params_x, P_t, prop_sig_thetas, prop_sig_thetas_x_density, xs_lwr, xs_upr, x_grd_res, var_grd_res, e_grd_res, alpha_x, a_sigmasq_x, b_sigmasq_x, K_x, a_vartheta, b_vartheta, type_v, K_t, type_u, K_epsilon, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, a_xi, b_xi, sigmasq_xi, a_beta, b_beta, sigmasq_beta, mu0_thetas_eps, sigma00_thetas_eps, sig_tune_theta_1, sig_tune_theta_2, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// mcmcuniepi_cpp
Rcpp::List mcmcuniepi_cpp(arma::uword nsamp, arma::uword nburn, arma::uword nthin, arma::uword niter_u, arma::vec ws, arma::vec xs, arma::vec us, arma::uvec mis, arma::uvec inds, double xs_lwr, double xs_upr, bool type_v, arma::uword K_t, arma::vec knots_t, arma::vec thetas, arma::mat P_t, arma::uword x_grd_res, arma::uword e_grd_res, arma::uword var_grd_res, arma::vec thetas_xs_density, arma::uword type_u, arma::uword K_epsilon, double a_vartheta, double b_vartheta, double sigmasq_vartheta, double a_beta, double b_beta, double sigmasq_beta, double a_xi, double b_xi, double sigmasq_xi, double alpha_epsilon, double a_epsilon, double b_epsilon, double sigmasq_epsilon, arma::vec mu0_thetas_eps, arma::mat sigma0_thetas_eps, arma::mat prop_sig_thetas_xs_density, arma::mat prop_sig_thetas, double sig_tune_thetas_1, double sig_tune_thetas_2, bool show_progress);
RcppExport SEXP _BayesDecon_mcmcuniepi_cpp(SEXP nsampSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP niter_uSEXP, SEXP wsSEXP, SEXP xsSEXP, SEXP usSEXP, SEXP misSEXP, SEXP indsSEXP, SEXP xs_lwrSEXP, SEXP xs_uprSEXP, SEXP type_vSEXP, SEXP K_tSEXP, SEXP knots_tSEXP, SEXP thetasSEXP, SEXP P_tSEXP, SEXP x_grd_resSEXP, SEXP e_grd_resSEXP, SEXP var_grd_resSEXP, SEXP thetas_xs_densitySEXP, SEXP type_uSEXP, SEXP K_epsilonSEXP, SEXP a_varthetaSEXP, SEXP b_varthetaSEXP, SEXP sigmasq_varthetaSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP sigmasq_betaSEXP, SEXP a_xiSEXP, SEXP b_xiSEXP, SEXP sigmasq_xiSEXP, SEXP alpha_epsilonSEXP, SEXP a_epsilonSEXP, SEXP b_epsilonSEXP, SEXP sigmasq_epsilonSEXP, SEXP mu0_thetas_epsSEXP, SEXP sigma0_thetas_epsSEXP, SEXP prop_sig_thetas_xs_densitySEXP, SEXP prop_sig_thetasSEXP, SEXP sig_tune_thetas_1SEXP, SEXP sig_tune_thetas_2SEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type niter_u(niter_uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type us(usSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mis(misSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type inds(indsSEXP);
    Rcpp::traits::input_parameter< double >::type xs_lwr(xs_lwrSEXP);
    Rcpp::traits::input_parameter< double >::type xs_upr(xs_uprSEXP);
    Rcpp::traits::input_parameter< bool >::type type_v(type_vSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_t(K_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type knots_t(knots_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_t(P_tSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type x_grd_res(x_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type e_grd_res(e_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type var_grd_res(var_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetas_xs_density(thetas_xs_densitySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type type_u(type_uSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_epsilon(K_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type a_vartheta(a_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type b_vartheta(b_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_vartheta(sigmasq_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_beta(sigmasq_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_xi(a_xiSEXP);
    Rcpp::traits::input_parameter< double >::type b_xi(b_xiSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_xi(sigmasq_xiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_epsilon(alpha_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type a_epsilon(a_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type b_epsilon(b_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_epsilon(sigmasq_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0_thetas_eps(mu0_thetas_epsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma0_thetas_eps(sigma0_thetas_epsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prop_sig_thetas_xs_density(prop_sig_thetas_xs_densitySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prop_sig_thetas(prop_sig_thetasSEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_thetas_1(sig_tune_thetas_1SEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_thetas_2(sig_tune_thetas_2SEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcuniepi_cpp(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, thetas_xs_density, type_u, K_epsilon, a_vartheta, b_vartheta, sigmasq_vartheta, a_beta, b_beta, sigmasq_beta, a_xi, b_xi, sigmasq_xi, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, mu0_thetas_eps, sigma0_thetas_eps, prop_sig_thetas_xs_density, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// mcmcunireg_cpp
Rcpp::List mcmcunireg_cpp(arma::uword nsamp, arma::uword nburn, arma::uword nthin, arma::uword niter_u, arma::vec ws, arma::vec xs, arma::vec us, arma::uvec mis, arma::uvec inds, double xs_lwr, double xs_upr, arma::vec srvywgt, bool type_v, arma::uword K_t, arma::vec knots_t, arma::vec thetas, arma::mat P_t, arma::uword x_grd_res, arma::uword e_grd_res, arma::uword var_grd_res, arma::uword K_x, arma::vec pi_xs, arma::uvec z_xs, arma::vec mu_xs, arma::vec sigmasq_xs, arma::uword type_u, arma::uword K_epsilon, double alpha_xs, double alpha_epsilon, double mu0_xs, double sigmasq0_xs, double a_sigmasq_xs, double b_sigmasq_xs, double a_epsilon, double b_epsilon, double sigmasq_epsilon, double sigmasq_vartheta, double a_vartheta, double b_vartheta, arma::mat prop_sig_thetas, double sig_tune_thetas_1, double sig_tune_thetas_2, bool use_wgt, bool show_progress);
RcppExport SEXP _BayesDecon_mcmcunireg_cpp(SEXP nsampSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP niter_uSEXP, SEXP wsSEXP, SEXP xsSEXP, SEXP usSEXP, SEXP misSEXP, SEXP indsSEXP, SEXP xs_lwrSEXP, SEXP xs_uprSEXP, SEXP srvywgtSEXP, SEXP type_vSEXP, SEXP K_tSEXP, SEXP knots_tSEXP, SEXP thetasSEXP, SEXP P_tSEXP, SEXP x_grd_resSEXP, SEXP e_grd_resSEXP, SEXP var_grd_resSEXP, SEXP K_xSEXP, SEXP pi_xsSEXP, SEXP z_xsSEXP, SEXP mu_xsSEXP, SEXP sigmasq_xsSEXP, SEXP type_uSEXP, SEXP K_epsilonSEXP, SEXP alpha_xsSEXP, SEXP alpha_epsilonSEXP, SEXP mu0_xsSEXP, SEXP sigmasq0_xsSEXP, SEXP a_sigmasq_xsSEXP, SEXP b_sigmasq_xsSEXP, SEXP a_epsilonSEXP, SEXP b_epsilonSEXP, SEXP sigmasq_epsilonSEXP, SEXP sigmasq_varthetaSEXP, SEXP a_varthetaSEXP, SEXP b_varthetaSEXP, SEXP prop_sig_thetasSEXP, SEXP sig_tune_thetas_1SEXP, SEXP sig_tune_thetas_2SEXP, SEXP use_wgtSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type niter_u(niter_uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type us(usSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type mis(misSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type inds(indsSEXP);
    Rcpp::traits::input_parameter< double >::type xs_lwr(xs_lwrSEXP);
    Rcpp::traits::input_parameter< double >::type xs_upr(xs_uprSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type srvywgt(srvywgtSEXP);
    Rcpp::traits::input_parameter< bool >::type type_v(type_vSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_t(K_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type knots_t(knots_tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P_t(P_tSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type x_grd_res(x_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type e_grd_res(e_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type var_grd_res(var_grd_resSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_x(K_xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi_xs(pi_xsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type z_xs(z_xsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_xs(mu_xsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigmasq_xs(sigmasq_xsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type type_u(type_uSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K_epsilon(K_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_xs(alpha_xsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_epsilon(alpha_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type mu0_xs(mu0_xsSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq0_xs(sigmasq0_xsSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigmasq_xs(a_sigmasq_xsSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigmasq_xs(b_sigmasq_xsSEXP);
    Rcpp::traits::input_parameter< double >::type a_epsilon(a_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type b_epsilon(b_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_epsilon(sigmasq_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_vartheta(sigmasq_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type a_vartheta(a_varthetaSEXP);
    Rcpp::traits::input_parameter< double >::type b_vartheta(b_varthetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prop_sig_thetas(prop_sig_thetasSEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_thetas_1(sig_tune_thetas_1SEXP);
    Rcpp::traits::input_parameter< double >::type sig_tune_thetas_2(sig_tune_thetas_2SEXP);
    Rcpp::traits::input_parameter< bool >::type use_wgt(use_wgtSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcunireg_cpp(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, srvywgt, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, K_x, pi_xs, z_xs, mu_xs, sigmasq_xs, type_u, K_epsilon, alpha_xs, alpha_epsilon, mu0_xs, sigmasq0_xs, a_sigmasq_xs, b_sigmasq_xs, a_epsilon, b_epsilon, sigmasq_epsilon, sigmasq_vartheta, a_vartheta, b_vartheta, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, use_wgt, show_progress));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm
arma::vec dmvnorm(arma::mat const& x, arma::rowvec const& mean, arma::mat const& sigma, bool const logd);
RcppExport SEXP _BayesDecon_dmvnorm(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec const& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool const >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm_sclr
double dtnorm_sclr(double x, double mean, double sd, double lwr, double upr, bool log);
RcppExport SEXP _BayesDecon_dtnorm_sclr(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lwrSEXP, SEXP uprSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lwr(lwrSEXP);
    Rcpp::traits::input_parameter< double >::type upr(uprSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm_sclr(x, mean, sd, lwr, upr, log));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm
arma::vec dtnorm(arma::vec x, double mean, double sd, double lwr, double upr, bool log);
RcppExport SEXP _BayesDecon_dtnorm(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lwrSEXP, SEXP uprSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lwr(lwrSEXP);
    Rcpp::traits::input_parameter< double >::type upr(uprSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm(x, mean, sd, lwr, upr, log));
    return rcpp_result_gen;
END_RCPP
}
// ptnorm
arma::vec ptnorm(arma::vec q, double mean, double sd, double lwr, double upr, bool lower_tail, bool log_p);
RcppExport SEXP _BayesDecon_ptnorm(SEXP qSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lwrSEXP, SEXP uprSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lwr(lwrSEXP);
    Rcpp::traits::input_parameter< double >::type upr(uprSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(ptnorm(q, mean, sd, lwr, upr, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
arma::vec rtnorm(arma::uword n, double mean, double sd, double lwr, double upr);
RcppExport SEXP _BayesDecon_rtnorm(SEXP nSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP lwrSEXP, SEXP uprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lwr(lwrSEXP);
    Rcpp::traits::input_parameter< double >::type upr(uprSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(n, mean, sd, lwr, upr));
    return rcpp_result_gen;
END_RCPP
}
// rmvtnorm
arma::vec rmvtnorm(arma::vec alpha, arma::vec beta, arma::mat cov);
RcppExport SEXP _BayesDecon_rmvtnorm(SEXP alphaSEXP, SEXP betaSEXP, SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvtnorm(alpha, beta, cov));
    return rcpp_result_gen;
END_RCPP
}
// rmvtnorm_mono
arma::vec rmvtnorm_mono(arma::vec mean, arma::mat cov);
RcppExport SEXP _BayesDecon_rmvtnorm_mono(SEXP meanSEXP, SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvtnorm_mono(mean, cov));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesDecon_chk_omp", (DL_FUNC) &_BayesDecon_chk_omp, 0},
    {"_BayesDecon_formcorr", (DL_FUNC) &_BayesDecon_formcorr, 2},
    {"_BayesDecon_mcmcmvt_cpp", (DL_FUNC) &_BayesDecon_mcmcmvt_cpp, 57},
    {"_BayesDecon_mcmcuniepi_cpp", (DL_FUNC) &_BayesDecon_mcmcuniepi_cpp, 42},
    {"_BayesDecon_mcmcunireg_cpp", (DL_FUNC) &_BayesDecon_mcmcunireg_cpp, 44},
    {"_BayesDecon_dmvnorm", (DL_FUNC) &_BayesDecon_dmvnorm, 4},
    {"_BayesDecon_dtnorm_sclr", (DL_FUNC) &_BayesDecon_dtnorm_sclr, 6},
    {"_BayesDecon_dtnorm", (DL_FUNC) &_BayesDecon_dtnorm, 6},
    {"_BayesDecon_ptnorm", (DL_FUNC) &_BayesDecon_ptnorm, 7},
    {"_BayesDecon_rtnorm", (DL_FUNC) &_BayesDecon_rtnorm, 5},
    {"_BayesDecon_rmvtnorm", (DL_FUNC) &_BayesDecon_rmvtnorm, 3},
    {"_BayesDecon_rmvtnorm_mono", (DL_FUNC) &_BayesDecon_rmvtnorm_mono, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesDecon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
