# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chk_omp <- function() {
    .Call(`_BayesDecon_chk_omp`)
}

formcorr <- function(b, theta) {
    .Call(`_BayesDecon_formcorr`, b, theta)
}

mcmcmvt_cpp <- function(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, p, q, knots_t, delta_t, thetas, theta_x, z_u, pi_u, ic, inc, x_e, x_nz, theta_e, z_x, pi_x, params_x, P_t, prop_sig_thetas, prop_sig_thetas_x_density, xs_lwr, xs_upr, x_grd_res, var_grd_res, e_grd_res, alpha_x, a_sigmasq_x, b_sigmasq_x, K_x, a_vartheta, b_vartheta, type_v, K_t, type_u, K_epsilon, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, a_xi, b_xi, sigmasq_xi, a_beta, b_beta, sigmasq_beta, mu0_thetas_eps, sigma00_thetas_eps, sig_tune_theta_1, sig_tune_theta_2, show_progress) {
    .Call(`_BayesDecon_mcmcmvt_cpp`, nsamp, nburn, nthin, niter_u, ws, xs, us, mis, p, q, knots_t, delta_t, thetas, theta_x, z_u, pi_u, ic, inc, x_e, x_nz, theta_e, z_x, pi_x, params_x, P_t, prop_sig_thetas, prop_sig_thetas_x_density, xs_lwr, xs_upr, x_grd_res, var_grd_res, e_grd_res, alpha_x, a_sigmasq_x, b_sigmasq_x, K_x, a_vartheta, b_vartheta, type_v, K_t, type_u, K_epsilon, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, a_xi, b_xi, sigmasq_xi, a_beta, b_beta, sigmasq_beta, mu0_thetas_eps, sigma00_thetas_eps, sig_tune_theta_1, sig_tune_theta_2, show_progress)
}

mcmcuniepi_cpp <- function(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, thetas_xs_density, type_u, K_epsilon, a_vartheta, b_vartheta, sigmasq_vartheta, a_beta, b_beta, sigmasq_beta, a_xi, b_xi, sigmasq_xi, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, mu0_thetas_eps, sigma0_thetas_eps, prop_sig_thetas_xs_density, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, show_progress) {
    .Call(`_BayesDecon_mcmcuniepi_cpp`, nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, thetas_xs_density, type_u, K_epsilon, a_vartheta, b_vartheta, sigmasq_vartheta, a_beta, b_beta, sigmasq_beta, a_xi, b_xi, sigmasq_xi, alpha_epsilon, a_epsilon, b_epsilon, sigmasq_epsilon, mu0_thetas_eps, sigma0_thetas_eps, prop_sig_thetas_xs_density, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, show_progress)
}

mcmcunireg_cpp <- function(nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, srvywgt, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, K_x, pi_xs, z_xs, mu_xs, sigmasq_xs, type_u, K_epsilon, alpha_xs, alpha_epsilon, mu0_xs, sigmasq0_xs, a_sigmasq_xs, b_sigmasq_xs, a_epsilon, b_epsilon, sigmasq_epsilon, sigmasq_vartheta, a_vartheta, b_vartheta, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, use_wgt, show_progress) {
    .Call(`_BayesDecon_mcmcunireg_cpp`, nsamp, nburn, nthin, niter_u, ws, xs, us, mis, inds, xs_lwr, xs_upr, srvywgt, type_v, K_t, knots_t, thetas, P_t, x_grd_res, e_grd_res, var_grd_res, K_x, pi_xs, z_xs, mu_xs, sigmasq_xs, type_u, K_epsilon, alpha_xs, alpha_epsilon, mu0_xs, sigmasq0_xs, a_sigmasq_xs, b_sigmasq_xs, a_epsilon, b_epsilon, sigmasq_epsilon, sigmasq_vartheta, a_vartheta, b_vartheta, prop_sig_thetas, sig_tune_thetas_1, sig_tune_thetas_2, use_wgt, show_progress)
}

dmvnorm <- function(x, mean, sigma, logd) {
    .Call(`_BayesDecon_dmvnorm`, x, mean, sigma, logd)
}

dtnorm_sclr <- function(x, mean, sd, lwr, upr, log) {
    .Call(`_BayesDecon_dtnorm_sclr`, x, mean, sd, lwr, upr, log)
}

dtnorm <- function(x, mean, sd, lwr, upr, log) {
    .Call(`_BayesDecon_dtnorm`, x, mean, sd, lwr, upr, log)
}

ptnorm <- function(q, mean, sd, lwr, upr, lower_tail, log_p) {
    .Call(`_BayesDecon_ptnorm`, q, mean, sd, lwr, upr, lower_tail, log_p)
}

rtnorm <- function(n, mean, sd, lwr, upr) {
    .Call(`_BayesDecon_rtnorm`, n, mean, sd, lwr, upr)
}

rmvtnorm <- function(alpha, beta, cov) {
    .Call(`_BayesDecon_rmvtnorm`, alpha, beta, cov)
}

rmvtnorm_mono <- function(mean, cov) {
    .Call(`_BayesDecon_rmvtnorm_mono`, mean, cov)
}

